global using Microsoft.AspNetCore.Mvc;
global using Newtonsoft.Json;
global using System.Text;
global using YamyProject.Core.Models;
global using YamyProject.Core.ViewModel;
global using YamyProject.Filters;
global using YamyProject.Data;
global using MySqlConnector;
global using System.Diagnostics;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Cryptography.KeyDerivation;
global using System.Security.Cryptography;
global using AutoMapper;
global using System.ComponentModel.DataAnnotations.Schema;
global using YamyProject.Core.ViewModel.YourApp.ViewModels;
global using YamyProject.Services.Interfaces;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Mvc.Rendering;

