global using Microsoft.AspNetCore.Mvc;
global using Newtonsoft.Json;
global using System.Text;
global using YamyProject.Models;
global using System.Diagnostics;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Cryptography.KeyDerivation;
global using System.Security.Cryptography;
global using MySqlConnector;
